SerialPassthrough - PlatformIO: src/SerialPassthrough.cpp File Reference
SerialPassthrough.cpp File Reference
Link serial trafic between Seria0 / Serial1 (and Serial2 / Serial3)
#include <avr/io.h>
#include <util/delay.h>
#include "Serial.h"
Macros
#define AVR_LIBS 1
#define ARDU_LIBS 2
#define LIBS AVR_LIBS
#define TXmode 3
#define TXRXmode 4
#define Testmode RXTXmode
#define F_CPU 2566666L
Functions
void led_toggle (void)
int main (void)
Detailed Description
Link serial trafic between Seria0 / Serial1 (and Serial2 / Serial3)
Author
jzupan
Date
2023/24
Note
Tested on Arduino NANO Every board (Atmega4809 CPU)
This testing code:
Arduino library:
-  Sending bytes on Serial, and Serial1 every 300ms    or
-  Receiving bytes from Serial and transmitting to Serial1 and vice versa.
AVR libraries (without any use of ISRs):
-  Sending bytes on UART0, UART1, UART2, UART3 every 500ms    or
-  Receiving bytes from UART0 and transmitting to USART1 and vice versa and
   Receiving bytes from UART2 and transmitting to USART3 and vice versa.
Atmega4809 CPU 20MHz, (28,32,40,48 pin):
Flash size 48kb, SRAM 6kb, EEPROM 256b, 4x 16-bit Timers, RTC, 4x USART, 1X WDT
1x TWI 100/400/1000 kHz, 1x(16) 10-bit AD lines, 1x Custom Logic (LUT), ...
Definition in file SerialPassthrough.cpp.
Macro Definition Documentation
ARDU_LIBS
#define ARDU_LIBS 2
Definition at line 25 of file SerialPassthrough.cpp.
AVR_LIBS
#define AVR_LIBS 1
Definition at line 24 of file SerialPassthrough.cpp.
F_CPU
#define F_CPU 2566666L
Arduino NANO EVERY modul
Definition at line 40 of file SerialPassthrough.cpp.
LIBS
#define LIBS AVR_LIBS
Definition at line 26 of file SerialPassthrough.cpp.
Testmode
#define Testmode RXTXmode
Definition at line 30 of file SerialPassthrough.cpp.
TXmode
#define TXmode 3
Definition at line 28 of file SerialPassthrough.cpp.
TXRXmode
#define TXRXmode 4
Definition at line 29 of file SerialPassthrough.cpp.
Function Documentation
led_toggle()
void led_toggle (void)
Definition at line 120 of file SerialPassthrough.cpp.
main()
int main (void)
Definition at line 127 of file SerialPassthrough.cpp.
References led_toggle(), portmux_init(), uart0_init(), uart0_receive_nonblocking(), uart0_send(), uart1_init(), uart1_send(), uart2_init(), uart2_receive_nonblocking(), uart2_send(), uart3_init(), and uart3_send().