SerialPassthrough - PlatformIO: src/Serial.cpp File Reference
Serial.cpp File Reference
Support code for USART0,1,2,3.
#include <avr/io.h>
#include <util/delay.h>
Functions
void portmux_init (void)
uint16_t calc_baud (uint32_t baud_rate, uint32_t f_cpu)
void uart0_init (uint32_t baud_rate)
void uart1_init (uint32_t baud_rate)
void uart2_init (uint32_t baud_rate)
void uart3_init (uint32_t baud_rate)
void uart0_send (char data)
void uart1_send (char data)
void uart2_send (char data)
void uart3_send (char data)
char uart0_receive (void)
char uart0_receive_nonblocking (void)
char uart1_receive (void)
char uart1_receive_nonblocking (void)
char uart2_receive (void)
char uart2_receive_nonblocking (void)
char uart3_receive (void)
char uart3_receive_nonblocking (void)
Detailed Description
Support code for USART0,1,2,3.
Author
jzupan
Date
2023/24
Definition in file Serial.cpp.
Function Documentation
calc_baud()
uint16_t calc_baud (uint32_t baud_rate, uint32_t f_cpu)
Definition at line 26 of file Serial.cpp.
portmux_init()
void portmux_init (void)
Definition at line 18 of file Serial.cpp.
uart0_init()
void uart0_init (uint32_t baud_rate)
Definition at line 30 of file Serial.cpp.
References calc_baud(), and F_CPU.
uart0_receive()
char uart0_receive (void)
Definition at line 87 of file Serial.cpp.
uart0_receive_nonblocking()
char uart0_receive_nonblocking (void)
Definition at line 91 of file Serial.cpp.
uart0_send()
void uart0_send (char data)
Definition at line 67 of file Serial.cpp.
uart1_init()
void uart1_init (uint32_t baud_rate)
Definition at line 39 of file Serial.cpp.
References calc_baud(), and F_CPU.
uart1_receive()
char uart1_receive (void)
Definition at line 98 of file Serial.cpp.
uart1_receive_nonblocking()
char uart1_receive_nonblocking (void)
Definition at line 102 of file Serial.cpp.
uart1_send()
void uart1_send (char data)
Definition at line 72 of file Serial.cpp.
uart2_init()
void uart2_init (uint32_t baud_rate)
Definition at line 48 of file Serial.cpp.
References calc_baud(), and F_CPU.
uart2_receive()
char uart2_receive (void)
Definition at line 108 of file Serial.cpp.
uart2_receive_nonblocking()
char uart2_receive_nonblocking (void)
Definition at line 112 of file Serial.cpp.
uart2_send()
void uart2_send (char data)
Definition at line 77 of file Serial.cpp.
uart3_init()
void uart3_init (uint32_t baud_rate)
Definition at line 57 of file Serial.cpp.
References calc_baud(), and F_CPU.
uart3_receive()
char uart3_receive (void)
Definition at line 118 of file Serial.cpp.
uart3_receive_nonblocking()
char uart3_receive_nonblocking (void)
Definition at line 122 of file Serial.cpp.
uart3_send()
void uart3_send (char data)
Definition at line 82 of file Serial.cpp.